image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:cw-bump-leeway.29
workspaceLocation: gitpod/gitpod-ws.code-workspace
checkoutLocation: gitpod
ports:
  - port: 1337
    onOpen: open-preview
  - port: 3000
    onOpen: ignore
  - port: 3001
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  - port: 4000
    onOpen: ignore
  - port: 9229
    onOpen: ignore
# Go proxy
  - port: 9999
    onOpen: ignore
  - port: 13001
    onOpen: ignore
# Werft
  - port: 7777
    onOpen: ignore
# Dev Theia
  - port: 13444
tasks:
  - name: TEST
    init: echo "VISIBLE $VISIBLE, CENSORED $CENSORED"
    command: echo "VISIBLE $VISIBLE, CENSORED $CENSORED"
vscode:
  extensions:
    - bajdzis.vscode-database
    - bradlc.vscode-tailwindcss
    - EditorConfig.EditorConfig
    - golang.go
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - stkb.rewrap
    - zxh404.vscode-proto3
    - matthewpi.caddyfile-support
    - heptio.jsonnet
    - timonwong.shellcheck
    - vscjava.vscode-java-pack
    - fwcd.kotlin
