# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License-AGPL.txt in the project root for license information.

---
gitpod_domain: gitpod.testing.gitpod-self-hosted.com

gcp_project: gitpod-self-hosted-testing
gcp_bucket_name: gitpod-self-hosted-testing-backups

gcp_dns_project: dns-for-playgrounds
gcp_dns_domain_zone_name: gitpod-self-hosted-com
gcp_dns_domain_zone_dnsname: gitpod-self-hosted.com.

installCertManager: false
