packages:
  - name: docker
    type: docker
    srcs:
      - "entrypoint.sh"
      - "ansible/**/*"
    deps:
      - components/installer:app
      - test:app
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      image:
        - ${imageRepoBase}/test-installations:${version}
        - ${imageRepoBase}/test-installations:commit-${__git_commit}
